package util;

import model.Ponto;
import model.Rota;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;

/**
 * Exporta relatórios em formato PDF sem dependência externa.
 * Gera um PDF textual simples, suficiente para relatórios do sistema.
 */
public class PDFExporter {

    private static final int LINES_PER_PAGE = 42;

    public static void exportarRelatorio(
            Rota rota,
            String algoritmo,
            List<Ponto> todosPontos,
            File arquivo
    ) throws IOException {
        if (rota == null) {
            throw new IllegalArgumentException("A rota não pode ser nula.");
        }
        if (arquivo == null) {
            throw new IllegalArgumentException("O arquivo de saída não pode ser nulo.");
        }

        List<String> linhas = construirLinhas(rota, algoritmo, todosPontos);
        escreverPdf(linhas, arquivo);
    }

    private static List<String> construirLinhas(
            Rota rota,
            String algoritmo,
            List<Ponto> todosPontos
    ) {
        List<String> linhas = new ArrayList<>();

        linhas.add("RELATORIO DE ROTA - TRANSPORTE UNIVERSITARIO");
        linhas.add("Cruz das Almas - Bahia");
        linhas.add("");
        linhas.add("INFORMACOES GERAIS");
        linhas.add("Algoritmo utilizado: " + valorOuPadrao(algoritmo));
        linhas.add("Numero total de pontos: " + (todosPontos != null ? todosPontos.size() : 0));
        linhas.add("");
        linhas.add("ESTATISTICAS DA ROTA");
        linhas.add(String.format("Distancia total: %.2f km", rota.getDistanciaTotal()));
        linhas.add(String.format("Tempo estimado: %.2f min", rota.getTempoTotal()));
        linhas.add("Estudantes atendidos: " + rota.calcularTotalAlunos());
        linhas.add("Numero de paradas: " + rota.getPercurso().size());
        linhas.add(String.format("Combustivel estimado: %.2f litros (5 km/L)",
                GeoUtils.estimarCombustivel(rota.getDistanciaTotal(), 5.0)));
        linhas.add("");
        linhas.add("ORDEM DAS PARADAS");

        int ordem = 1;
        for (Ponto p : rota.getPercurso()) {
            linhas.add(String.format("%d. %s | %s | %.6f, %.6f | %d alunos",
                    ordem++,
                    p.getNome(),
                    p.getTipo().getRotulo(),
                    p.getLatitude(),
                    p.getLongitude(),
                    p.getQuantidadeAlunos()));
        }

        linhas.add("");
        linhas.add("Gerado em: " + java.time.LocalDateTime.now());
        return linhas;
    }

    private static String valorOuPadrao(String valor) {
        return valor == null || valor.trim().isEmpty() ? "-" : valor;
    }

    private static void escreverPdf(List<String> linhas, File arquivo) throws IOException {
        int paginas = Math.max(1, (linhas.size() + LINES_PER_PAGE - 1) / LINES_PER_PAGE);
        int fontObjectId = 3 + (paginas * 2);

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        List<Integer> offsets = new ArrayList<>();

        write(out, "%PDF-1.4\n");
        write(out, "% Simple PDF generated by PDFExporter\n");

        // 1: Catalog
        offsets.add(out.size());
        writeObject(out, "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");

        // 2: Pages
        offsets.add(out.size());
        StringBuilder kids = new StringBuilder();
        for (int i = 0; i < paginas; i++) {
            int pageObjectId = 3 + (i * 2);
            kids.append(pageObjectId).append(" 0 R ");
        }
        writeObject(out, "2 0 obj\n<< /Type /Pages /Kids [" + kids + "] /Count " + paginas + " >>\nendobj\n");

        // Pages and content objects
        for (int i = 0; i < paginas; i++) {
            int pageObjectId = 3 + (i * 2);
            int contentObjectId = pageObjectId + 1;
            int start = i * LINES_PER_PAGE;
            int end = Math.min(start + LINES_PER_PAGE, linhas.size());
            String contentStream = montarStream(linhas.subList(start, end));

            offsets.add(out.size());
            writeObject(out,
                    pageObjectId + " 0 obj\n" +
                            "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] " +
                            "/Resources << /Font << /F1 " + fontObjectId + " 0 R >> >> " +
                            "/Contents " + contentObjectId + " 0 R >>\n" +
                            "endobj\n");

            byte[] contentBytes = contentStream.getBytes(StandardCharsets.ISO_8859_1);
            offsets.add(out.size());
            write(out, contentObjectId + " 0 obj\n");
            write(out, "<< /Length " + contentBytes.length + " >>\nstream\n");
            out.write(contentBytes);
            write(out, "\nendstream\nendobj\n");
        }

        // Font
        offsets.add(out.size());
        writeObject(out, fontObjectId + " 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n");

        int startXref = out.size();
        int totalObjects = fontObjectId;

        write(out, "xref\n");
        write(out, "0 " + (totalObjects + 1) + "\n");
        write(out, "0000000000 65535 f \n");
        for (int offset : offsets) {
            write(out, String.format("%010d 00000 n \n", offset));
        }

        write(out, "trailer\n");
        write(out, "<< /Size " + (totalObjects + 1) + " /Root 1 0 R >>\n");
        write(out, "startxref\n");
        write(out, String.valueOf(startXref) + "\n");
        write(out, "%%EOF");

        try (FileOutputStream fos = new FileOutputStream(arquivo)) {
            out.writeTo(fos);
        }
    }

    private static String montarStream(List<String> linhas) {
        StringBuilder sb = new StringBuilder();
        sb.append("BT\n");
        sb.append("/F1 12 Tf\n");
        sb.append("50 800 Td\n");
        sb.append("14 TL\n");

        for (String linha : linhas) {
            sb.append("(")
                    .append(escaparPdf(normalizar(linha)))
                    .append(") Tj\n");
            sb.append("T*\n");
        }

        sb.append("ET");
        return sb.toString();
    }

    private static String normalizar(String texto) {
        if (texto == null) {
            return "";
        }

        String normalizado = Normalizer.normalize(texto, Normalizer.Form.NFD)
                .replaceAll("\\p{M}+", "");
        normalizado = normalizado
                .replace('–', '-')
                .replace('—', '-')
                .replace('→', '-')
                .replace('“', '"')
                .replace('”', '"')
                .replace('’', '\'');
        return normalizado.replaceAll("[^\\x20-\\x7E]", " ");
    }

    private static String escaparPdf(String texto) {
        return texto
                .replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)");
    }

    private static void write(ByteArrayOutputStream out, String texto) throws IOException {
        out.write(texto.getBytes(StandardCharsets.ISO_8859_1));
    }

    private static void writeObject(ByteArrayOutputStream out, String objeto) throws IOException {
        write(out, objeto);
    }
}
